name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: freebsd
    steps:
      - uses: actions/checkout@v2
      - name: run default Makefile target
        run: make
